package com.jamanot.app.auth;

import android.app.Activity;
import android.content.Context;
import android.os.CancellationSignal;
import android.util.Log;

import androidx.credentials.CredentialManager;
import androidx.credentials.CredentialManagerCallback;
import androidx.credentials.CustomCredential;
import androidx.credentials.GetCredentialRequest;
import androidx.credentials.GetCredentialResponse;
import androidx.credentials.exceptions.GetCredentialCancellationException;
import androidx.credentials.exceptions.GetCredentialException;
import androidx.credentials.exceptions.NoCredentialException;

import com.getcapacitor.JSObject;
import com.getcapacitor.Plugin;
import com.getcapacitor.PluginCall;
import com.getcapacitor.PluginMethod;
import com.getcapacitor.annotation.CapacitorPlugin;
import com.google.android.libraries.identity.googleid.GetGoogleIdOption;
import com.google.android.libraries.identity.googleid.GetSignInWithGoogleOption;
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential;
import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.auth.GoogleAuthProvider;
import com.jamanot.app.R;

import java.util.concurrent.Executor;
import java.util.concurrent.Executors;

/**
 * Native Google sign-in via Android's Credential Manager.
 *
 * <p>Written by hand rather than pulling in a third-party Firebase auth plugin,
 * for one structural reason: this returns <i>only an ID token</i>. The web layer
 * then calls {@code signInWithCredential} itself, so the JS SDK owns the session
 * that {@code onAuthStateChanged} observes and the rest of AuthContext is
 * untouched. A plugin that creates its own session would leave two sessions to
 * keep in step.
 *
 * <p>It <i>also</i> signs in native FirebaseAuth with the same credential. That
 * costs three lines and prevents a guaranteed future outage: the Java Firestore
 * listener in DutyForegroundService works today only because firestore.rules is
 * wide open, and the moment those rules require auth an unsigned native session
 * would go dark.
 *
 * <p>Three things break this if misconfigured, all outside the code:
 * <ol>
 *   <li><b>SHA fingerprints.</b> Register SHA-1 <i>and</i> SHA-256 for the debug
 *       keystore, the upload keystore, and — after the first Play upload — Play
 *       App Signing's own. Missing the third is why sign-in works locally and
 *       fails from the Play build.</li>
 *   <li><b>Client ID.</b> {@code default_web_client_id} is generated by the
 *       google-services plugin from the <i>Web</i> OAuth client (client_type 3).
 *       Using the Android client ID yields DEVELOPER_ERROR / audience mismatch.</li>
 *   <li><b>Provider enablement.</b> Google must be enabled in Firebase
 *       Authentication with a support email set, or Credential Manager returns
 *       no credential at all.</li>
 * </ol>
 */
@CapacitorPlugin(name = "JamanotGoogleAuth")
public class GoogleAuthPlugin extends Plugin {

    private static final String TAG = "JamanotGoogleAuth";
    private static final String GOOGLE_ID_TOKEN_TYPE =
            "com.google.android.libraries.identity.googleid.TYPE_GOOGLE_ID_TOKEN_CREDENTIAL";

    private final Executor executor = Executors.newSingleThreadExecutor();

    @PluginMethod
    public void signIn(PluginCall call) {
        Activity activity = getActivity();
        if (activity == null) {
            call.reject("No activity available", "NO_ACTIVITY");
            return;
        }

        String webClientId = getWebClientId();
        if (webClientId == null || webClientId.isEmpty()) {
            call.reject(
                    "default_web_client_id is missing — add android/app/google-services.json",
                    "NO_CLIENT_ID");
            return;
        }

        // "Sign in with Google" always shows the account chooser, which is the
        // right behaviour behind an explicit sign-in button.
        GetSignInWithGoogleOption option =
                new GetSignInWithGoogleOption.Builder(webClientId).build();

        GetCredentialRequest request = new GetCredentialRequest.Builder()
                .addCredentialOption(option)
                .build();

        requestCredential(call, activity, request, true);
    }

    private void requestCredential(PluginCall call, Activity activity,
                                   GetCredentialRequest request, boolean allowFallback) {
        CredentialManager manager = CredentialManager.create(activity);
        manager.getCredentialAsync(
                activity,
                request,
                new CancellationSignal(),
                executor,
                new CredentialManagerCallback<GetCredentialResponse, GetCredentialException>() {
                    @Override
                    public void onResult(GetCredentialResponse response) {
                        handleResponse(call, response);
                    }

                    @Override
                    public void onError(GetCredentialException e) {
                        if (e instanceof GetCredentialCancellationException) {
                            // Dismissing the sheet is not an error worth alerting on.
                            call.reject("Sign-in cancelled", "CANCELLED");
                            return;
                        }
                        if (e instanceof NoCredentialException && allowFallback) {
                            // No account is currently offered — retry with the
                            // broader option that includes unauthorised accounts.
                            retryWithGoogleIdOption(call, activity);
                            return;
                        }
                        Log.w(TAG, "Credential request failed", e);
                        call.reject(e.getMessage() == null ? "Sign-in failed" : e.getMessage(),
                                "NO_CREDENTIAL");
                    }
                });
    }

    private void retryWithGoogleIdOption(PluginCall call, Activity activity) {
        String webClientId = getWebClientId();
        GetGoogleIdOption option = new GetGoogleIdOption.Builder()
                .setServerClientId(webClientId)
                .setFilterByAuthorizedAccounts(false)
                .setAutoSelectEnabled(false)
                .build();
        GetCredentialRequest request = new GetCredentialRequest.Builder()
                .addCredentialOption(option)
                .build();
        requestCredential(call, activity, request, false);
    }

    private void handleResponse(PluginCall call, GetCredentialResponse response) {
        try {
            if (!(response.getCredential() instanceof CustomCredential)
                    || !GOOGLE_ID_TOKEN_TYPE.equals(response.getCredential().getType())) {
                call.reject("Unexpected credential type", "NO_CREDENTIAL");
                return;
            }

            CustomCredential credential = (CustomCredential) response.getCredential();
            GoogleIdTokenCredential googleCredential =
                    GoogleIdTokenCredential.createFrom(credential.getData());

            String idToken = googleCredential.getIdToken();
            if (idToken == null || idToken.isEmpty()) {
                call.reject("No ID token returned", "NO_CREDENTIAL");
                return;
            }

            // Sign the native session in too — see the class javadoc.
            signInNative(idToken);

            JSObject result = new JSObject();
            result.put("idToken", idToken);
            result.put("email", googleCredential.getId());
            result.put("displayName", googleCredential.getDisplayName());
            result.put("photoUrl", googleCredential.getProfilePictureUri() == null
                    ? null : googleCredential.getProfilePictureUri().toString());
            call.resolve(result);

        } catch (Exception e) {
            Log.w(TAG, "Failed to read credential", e);
            call.reject(e.getMessage() == null ? "Sign-in failed" : e.getMessage(), "NO_CREDENTIAL");
        }
    }

    /**
     * Best-effort: the web session is what the app actually runs on, so a native
     * failure here must not fail the sign-in.
     */
    private void signInNative(String idToken) {
        try {
            FirebaseAuth.getInstance()
                    .signInWithCredential(GoogleAuthProvider.getCredential(idToken, null))
                    .addOnFailureListener(e -> Log.w(TAG, "Native session note: " + e.getMessage()));
        } catch (Exception e) {
            Log.w(TAG, "Native sign-in unavailable: " + e.getMessage());
        }
    }

    @PluginMethod
    public void signOut(PluginCall call) {
        try {
            FirebaseAuth.getInstance().signOut();
        } catch (Exception e) {
            Log.w(TAG, "Native sign-out note: " + e.getMessage());
        }
        try {
            // Clears the "previously signed in" state so the next sign-in shows
            // the chooser rather than silently reusing the last account.
            Context c = getContext();
            CredentialManager.create(c).clearCredentialStateAsync(
                    new androidx.credentials.ClearCredentialStateRequest(),
                    new CancellationSignal(),
                    executor,
                    new CredentialManagerCallback<Void,
                            androidx.credentials.exceptions.ClearCredentialException>() {
                        @Override
                        public void onResult(Void unused) {}

                        @Override
                        public void onError(
                                androidx.credentials.exceptions.ClearCredentialException e) {
                            Log.w(TAG, "clearCredentialState: " + e.getMessage());
                        }
                    });
        } catch (Exception e) {
            Log.w(TAG, "clearCredentialState unavailable: " + e.getMessage());
        }
        call.resolve();
    }

    /** Generated by the google-services Gradle plugin from google-services.json. */
    private String getWebClientId() {
        try {
            int id = getContext().getResources().getIdentifier(
                    "default_web_client_id", "string", getContext().getPackageName());
            return id == 0 ? null : getContext().getString(id);
        } catch (Exception e) {
            return null;
        }
    }
}
